<?php

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Дупница'
]);

$submit = $form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$submit->setValue($this->submitLabel);
$form->prepare();

?>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <?= $this->formElement($form->get('city_form_csrf')); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <?= $this->formElement($submit); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
