<?php

$form->get('name')->setAttributes([
	'class' => 'form-control',
	'placeholder' => 'Иван'
]);
$form->get('phone')->setAttributes([
	'class' => 'form-control',
	'placeholder' => '0887214253'
]);
$form->get('city_id')->setAttributes([
	'class' => 'form-control',
]);
$form->get('status')->setAttributes([
	'class' => 'form-control',
]);
$form->get('join_date_from')->setAttributes([
	'class' => 'form-control',
	'data-datepicker' => '',
]);
$form->get('join_date_to')->setAttributes([
	'class' => 'form-control',
	'data-datepicker' => '',
]);


$searchSubmit = $form->get('searchSubmit')->setAttributes(['class' => 'btn btn-primary']);
$searchSubmit->setValue('Търси');
$clearSubmit = $form->get('clearSubmit')->setAttributes(['class' => 'btn btn-primary']);
$clearSubmit->setValue('Изчисти');
$form->prepare();

$openSearchFormStyle = '';
if ($isOpenSearchForm) {
	$openSearchFormStyle = ' style="display: block"';
} else {
	$openSearchFormStyle = ' style="display: none"';
}
?>

<div class="row">
	<div class="col-md-6">
		<div id="searchForm">

			<h1>Търсене</h1>
			<div id="wrap-search-form" <?= $openSearchFormStyle ?> >
				<?= $this->form()->openTag($form); ?>

				<div class="form-group">
					<?= $this->formLabel($form->get('name')); ?>
					<?= $this->formElement($form->get('name')); ?>
					<?= $this->formElementErrors($form->get('name')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('phone')); ?>
					<?= $this->formElement($form->get('phone')); ?>
					<?= $this->formElementErrors($form->get('phone')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('city_id')); ?>
					<?= $this->formElement($form->get('city_id')); ?>
					<?= $this->formElementErrors($form->get('city_id')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('status')); ?>
					<?= $this->formElement($form->get('status')); ?>
					<?= $this->formElementErrors($form->get('status')); ?>
				</div>

				<div class="row">
					<div class="form-group col-md-5">
						<?= $this->formLabel($form->get('join_date_from')); ?>
						<?= $this->formElement($form->get('join_date_from')); ?>
						<?= $this->formElementErrors($form->get('join_date_from')); ?>
					</div>

					<div class="col-md-2 and">И</div>

					<div class="form-group col-md-5">
						<?= $this->formLabel($form->get('join_date_to')); ?>
						<?= $this->formElement($form->get('join_date_to')); ?>
						<?= $this->formElementErrors($form->get('join_date_to')); ?>
					</div>
				</div>

				<?= $this->formElement($searchSubmit); ?>
				<?= $this->formElement($clearSubmit); ?>

				<?= $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>


<script>
	/*jQuery time*/
	$(document).ready(function () {
		$("#searchForm h1").click(function () {
			//slide up all the link lists
			$("#wrap-search-form").slideUp();
			//slide down the link list below the h3 clicked - only if its closed
			if (!$(this).next().is(":visible")) {
				$(this).next().slideDown();
			}
		})
	})
</script>