<?php
$form->get('client_id')->setAttributes([
	'id' => 'clientId',
	'class' => 'form-control',
	'placeholder' => 'Ivan'
]);
$form->get('mbps')->setAttributes([
	'class' => 'form-control',
	'placeholder' => '20'
]);
$form->get('price')->setAttributes([
	'class' => 'form-control',
	'placeholder' => '20'
]);
$form->get('is_pay')->setAttributes([
	'class' => 'form-control',
]);
$form->get('payment_method')->setAttributes([
	'class' => 'form-control',
]);
$form->get('note')->setAttributes([
		'class' => 'form-control',
		'placeholder' => 'бележка за подсказка']
);
$submit = $form->get('submit')->setAttributes([
	'class' => 'btn btn-primary'
]);

if ($typeOrderForm == 'single') {
	$form->get('paid_at')->setAttributes([
		'class' => 'form-control',
		'placeholder' => '10.10.2016',
		'data-datepicker' => '',
	]);
} elseif ($typeOrderForm == 'multiple') {
	$form->get('paid_at_from')->setAttributes([
		'class' => 'form-control',
		'placeholder' => '10.10.2016',
		'data-datepicker' => '',
	]);
	$form->get('paid_at_to')->setAttributes([
		'class' => 'form-control',
		'placeholder' => '10.10.2016',
		'data-datepicker' => '',
	]);
}

$submit->setValue($this->submitLabel);
$form->prepare();

if ($isEdit) {
	$form->get('client_id')->setAttributes([
		'disabled' => 'disabled'
	]);
}

?>
<div class="row">
	<div class="col-md-6"><?= $this->form()->openTag($form); ?>
		<div class="form-group">
			<?= $this->formLabel($form->get('client_id')); ?>
			<?= $this->formElement($form->get('client_id')); ?>
			<?= $this->formElementErrors($form->get('client_id')); ?>
			<?= $this->formElement($form->get('city_id')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('mbps')); ?>
			<?= $this->formElement($form->get('mbps')); ?>
			<?= $this->formElementErrors($form->get('mbps')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('price')); ?>
			<?= $this->formElement($form->get('price')); ?>
			<?= $this->formElementErrors($form->get('price')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('is_pay')); ?>
			<?= $this->formElement($form->get('is_pay')); ?>
			<?= $this->formElementErrors($form->get('is_pay')); ?>
		</div>
		<div class="form-group">
			<?= $this->formLabel($form->get('payment_method')); ?>
			<?= $this->formElement($form->get('payment_method')); ?>
			<?= $this->formElementErrors($form->get('payment_method')); ?>
		</div>
		<?php if ($typeOrderForm == 'single') { ?>
			<div class="form-group">
				<?= $this->formLabel($form->get('paid_at')); ?>
				<?= $this->formElement($form->get('paid_at')); ?>
				<?= $this->formElementErrors($form->get('paid_at')); ?>
			</div>
		<?php } elseif ($typeOrderForm == 'multiple') { ?>
			<div class="form-group">
				<?= $this->formLabel($form->get('paid_at_from')); ?>
				<?= $this->formElement($form->get('paid_at_from')); ?>
				<?= $this->formElementErrors($form->get('paid_at_from')); ?>
			</div>
			<div class="form-group">
				<?= $this->formLabel($form->get('paid_at_to')); ?>
				<?= $this->formElement($form->get('paid_at_to')); ?>
				<?= $this->formElementErrors($form->get('paid_at_to')); ?>
			</div>
		<?php } ?>
		<div class="form-group">
			<?= $this->formLabel($form->get('note')); ?>
			<?= $this->formElement($form->get('note')); ?>
			<?= $this->formElementErrors($form->get('note')); ?>
		</div>
		<?= $this->formElement($submit); ?>
		<?= $this->form()->closeTag(); ?>
	</div>
</div>
<script>
	$(document).ready(function () {
		$('#clientId').change(function () {
			window.location.href = "?client_id=" + $(this).val();
		});
	});
</script>