<?php

$form->get('client_id')->setAttributes([
	'class' => 'form-control',
]);
$form->get('city_id')->setAttributes([
	'class' => 'form-control',
]);
$form->get('mbps')->setAttributes([
	'class' => 'form-control',
	'placeholder' => '20'
]);
$form->get('price')->setAttributes([
	'class' => 'form-control',
	'placeholder' => '15.00'
]);
$form->get('is_pay')->setAttributes([
	'class' => 'form-control',
]);
$form->get('paid_at_from')->setAttributes([
	'class' => 'form-control',
	'data-datepicker' => '',
]);
$form->get('paid_at_to')->setAttributes([
	'class' => 'form-control',
	'data-datepicker' => '',
]);


$searchSubmit = $form->get('searchSubmit')->setAttributes(['class' => 'btn btn-primary']);
$searchSubmit->setValue('Търси');
$clearSubmit = $form->get('clearSubmit')->setAttributes(['class' => 'btn btn-primary']);
$clearSubmit->setValue('Изчисти');
$form->prepare();

$openSearchFormStyle = '';
if ($isOpenSearchForm) {
	$openSearchFormStyle = ' style="display: block"';
} else {
	$openSearchFormStyle = ' style="display: none"';
}

?>

<div class="row">
	<div class="col-md-6">
		<div id="searchForm">

			<h1>Търсене</h1>
			<div id="wrap-search-form" <?= $openSearchFormStyle ?> >
				<?= $this->form()->openTag($form); ?>

				<div class="form-group">
					<?= $this->formLabel($form->get('client_id')); ?>
					<?= $this->formElement($form->get('client_id')); ?>
					<?= $this->formElementErrors($form->get('client_id')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('city_id')); ?>
					<?= $this->formElement($form->get('city_id')); ?>
					<?= $this->formElementErrors($form->get('city_id')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('mbps')); ?>
					<?= $this->formElement($form->get('mbps')); ?>
					<?= $this->formElementErrors($form->get('mbps')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('price')); ?>
					<?= $this->formElement($form->get('price')); ?>
					<?= $this->formElementErrors($form->get('price')); ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('is_pay')); ?>
					<?= $this->formElement($form->get('is_pay')); ?>
					<?= $this->formElementErrors($form->get('is_pay')); ?>
				</div>

				<div class="row">
					<div class="form-group col-md-5">
						<?= $this->formLabel($form->get('paid_at_from')); ?>
						<?= $this->formElement($form->get('paid_at_from')); ?>
						<?= $this->formElementErrors($form->get('paid_at_from')); ?>
					</div>

					<div class="col-md-2 and">AND</div>

					<div class="form-group col-md-5">
						<?= $this->formLabel($form->get('paid_at_to')); ?>
						<?= $this->formElement($form->get('paid_at_to')); ?>
						<?= $this->formElementErrors($form->get('paid_at_to')); ?>
					</div>
				</div>

				<?= $this->formElement($searchSubmit); ?>
				<?= $this->formElement($clearSubmit); ?>

				<?= $this->form()->closeTag(); ?>
			</div>
		</div>
	</div>
</div>


<script>
	/*jQuery time*/
	$(document).ready(function () {
		$("#searchForm h1").click(function () {
			//slide up all the link lists
			$("#wrap-search-form").slideUp();
			//slide down the link list below the h3 clicked - only if its closed
			if (!$(this).next().is(":visible")) {
				$(this).next().slideDown();
			}
		})
	})
</script>